snake_database/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('snakes.urls')),
    url(r'^snakes/', include('snakes.urls')),
    url(r'^snake/(?P<snake_id>\d+)', include('snakes.urls')),
    url(r'^admin/', admin.site.urls),
]

snakes/urls.py
from django.conf.urls import url

from snakes import views

urlpatterns = [
    url(r'^$', views.index, name='snakes'),
    url(r'^add/', views.add, name='add_snakes'),
    url(r'^edit/(?P<snake_id>\d+)', views.edit, name='edit_snake'),
    url(r'^delete/(?P<snake_id>\d+)', views.delete),
    url(r'^snake/(?P<snake_id>\d+)', views.view, name='view_snake'),
]

snakes/models.py
from django.db import models

# Create your models here.
class Snake(models.Model):
    common_name = models.CharField(max_length=50)
    species = models.CharField(max_length=100)
    location = models.CharField(max_length=50)
    description = models.CharField(max_length=300)

snakes/forms.py
from django import forms

from .models import Snake

class SnakeForm(forms.ModelForm):
    
    class Meta:
        model = Snake
        fields = ('common_name', 'species', 'location', 'description')

snakes/views.py
from django.shortcuts import render, redirect, get_list_or_404
#we need to import the redirect function for obvious reasons
from .forms import SnakeForm
from .models import Snake

# Create your views here.
def index(request):
    
    snakes = get_list_or_404(Snake)
    
    return render(request, 'index.html', {
        'snakes': snakes
    })

def add(request):
    
    if request.method == "POST":
        # We can process the form in here
        form = SnakeForm(request.POST)
        
        if form.is_valid():
            form.save()
        
        return redirect('snakes')
        
    else:
        form = SnakeForm
        return render(request, 'add.html', {
            'form': form
        })
    
def edit(request, snake_id):
    
    snake = Snake.objects.get(id=snake_id)
    
    if request.method == "POST":
        # We can process the form in here
        form = SnakeForm(request.POST, instance=snake)
        
        if form.is_valid():
            form.save()
        
        return redirect('snakes')
        
    else:
        form = SnakeForm
        return render(request, 'edit.html', {
            'form': form,
            'snake': snake
        })

def delete(request, snake_id):
    
    Snake.objects.get(id=snake_id).delete()
    return redirect('snakes')

def view(request, snake_id):
    
    snake = Snake.objects.get(id=snake_id)
    
    return render(request, 'view.html', {
        'snake': snake
    })

snake_database/templates/app.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Python Snake Database</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    

    {% block styles %}
    {% endblock %}
    
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>
<body>
    <nav class="navbar navbar-inverse">
        <ul class="nav navbar-nav">
            <li><a href="{% url 'snakes' %}">Snake Database</a></li>
            <li><a href="{% url 'add_snakes' %}">Add Snake</a></li>
        </ul>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    
    <script type="text/javascript" charset="utf8" src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.13/js/jquery.dataTables.js"></script>
    <script src="{% static 'js/app.js' %}"></script>
    {% block scripts %}
    {% endblock %}
</body>
</html>

snakes/templates/add.html
{% extends 'snake_database/templates/app.html' %}

{% block content %}
    <h1>Add Snake</h1>
    <hr>
    <form id="add-snake" method="post">
        {% csrf_token %}
<!--        {{ form.as_p }}-->
       <div class="form-group">
           <label for="id_common_name">Common Name:</label>
           <input type="text" class="form-control" name="common_name" maxlength="50" required>
       </div>
       <div class="form-group">
           <label for="id_species">Species:</label>
           <input type="text" class="form-control" name="species" maxlength="100" required>
       </div>
       <div class="form-group">
           <label for="id_location">Location:</label>
           <input type="text" class="form-control" name="location" maxlength="50" required>
       </div>
        <div class="form-group">
           <label for="id_description">Description:</label>
           <input type="text" class="form-control" name="description" maxlength="300" required>
       </div>
       <div class="form-group">
           <button type="submit" class="btn btn-info">Submit</button>
       </div>
    </form>
{% endblock %}

snakes/templates/edit.html
{% extends 'snake_database/templates/app.html' %}

{% block content %}
    <h1>Edit Snake</h1>
    <hr>
    <form id="edit-snake" method="post">
        {% csrf_token %}
<!--        {{ form.as_p }}-->
       <div class="form-group">
           <label for="id_common_name">Common Name:</label>
           <input type="text" class="form-control" name="common_name" value="{{ snake.common_name }}" maxlength="50" required>
       </div>
       <div class="form-group">
           <label for="id_species">Species:</label>
           <input type="text" class="form-control" name="species" value="{{ snake.species }}" maxlength="100" required>
       </div>
       <div class="form-group">
           <label for="id_location">Location:</label>
           <input type="text" class="form-control" name="location" value="{{ snake.location }}" maxlength="50" required>
       </div>
        <div class="form-group">
           <label for="id_description">Description:</label>
           <input type="text" class="form-control" name="description" value="{{ snake.description }}" maxlength="300" required>
       </div>
       <div class="form-group">
           <button type="submit" class="btn btn-info">Submit</button>
       </div>
    </form>
{% endblock %}

snakes/templates/index.html
{% extends 'snake_database/templates/app.html' %}

{% block styles %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/snakes.css' %}">
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.13/css/jquery.dataTables.css">
{% endblock %}

{% block content %}
    <h1>Snake Database</h1>
    


    <table id="snakes_table" class="table table-striped table-bordered" cellspacing="0" width="150%">
        <tr>
            <th>Common Name</th>
            <th>Species</th>
            <th>Location</th>
            <th>Description</th>
            <th style="width: 200px">Actions</th>
        </tr>
        {% for snake in snakes %}
        <tr>
            <td>{{ snake.common_name }} </td>
            <td>{{ snake.species }}</td>
            <td>{{ snake.location }}</td>
            <td>{{ snake.description }}</td>
            <td>
                <a href="/snake/{{snake.id}}" class="btn btn-info" role="button">View</a>
                <a href="/snakes/edit/{{snake.id}}" class="btn btn-info" role="button">Edit</a>
                <a href="/delete/{{snake.id}}" class="btn btn-info" role="button">Remove</a>
            </td>
        </tr>
        {% endfor %}
    </table>

{% endblock %}

{% block scripts %}
    <script>
    $(function(){
        $("#snakes_table").dataTable();
    })
    </script>
{% endblock %}

snakes/templates/view.html
{% extends 'snake_database/templates/app.html' %}



{% block content %}
    <h1>Snake Details</h1>
    
    <div class="panel panel-primary">
      <div class="panel-heading">{{ snake.common_name }} </div>
      <div class="panel-body">{{ snake.common_name }} is a species of {{ snake.species }} endemic to {{ snake.location }}. {{ snake.description }}</div>
    </div>
{% endblock %}